---
title: Language Feature Reference
sidebar_title: Language Feature Reference
---

This table outlines the types of OpenTelemetry instrumentation available for each language in the Demo.

| Language   | Automatic Instrumentation                                                                                                                                | Instrumentation Libraries                                                                    | Manual Instrumentation                                                                       |
| ---------- | -------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| .NET       | [Accounting Service](services/accounting/)                                                                                                               | [Cart Service](services/cart/)                                                               | [Cart Service](services/cart/)                                                               |
| C++        |                                                                                                                                                          |                                                                                              | [Currency Service](services/currency/)                                                       |
| Elixir     |                                                                                                                                                          | [Flagd-UI Service](services/flagd-ui/)                                                       |                                                                                              |
| Go         |                                                                                                                                                          | [Checkout Service](services/checkout/), [Product Catalog Service](services/product-catalog/) | [Checkout Service](services/checkout/), [Product Catalog Service](services/product-catalog/) |
| Java       | [Ad Service](services/ad/)                                                                                                                               |                                                                                              | [Ad Service](services/ad/)                                                                   |
| JavaScript | [Payment Service](services/payment/)                                                                                                                     |                                                                                              | [Payment Service](services/payment/)                                                         |
| TypeScript |                                                                                                                                                          | [Frontend](services/frontend/), [React Native App](services/react-native-app/)               | [Frontend](services/frontend/)                                                               |
| Kotlin     |                                                                                                                                                          | [Fraud Detection Service](services/fraud-detection/)                                         |                                                                                              |
| PHP        |                                                                                                                                                          | [Quote Service](services/quote/)                                                             | [Quote Service](services/quote/)                                                             |
| Python     | [Recommendation Service](services/recommendation/), [Agent Service](services/agent/), [Chatbot Service](services/chatbot/), [MCP Service](services/mcp/) |                                                                                              | [Recommendation Service](services/recommendation/)                                           |
| Ruby       |                                                                                                                                                          | [Email Service](services/email/)                                                             | [Email Service](services/email/)                                                             |
| Rust       |                                                                                                                                                          | [Shipping Service](services/shipping/)                                                       | [Shipping Service](services/shipping/)                                                       |
